name: Philip Long
title: PHILIP LONG
subtitle:  PhD, ROBOTICIST
description: > # this means to ignore newlines until "baseurl:"
     Website about Philip Long  
markdown: kramdown
future: true
gems:
    - jekyll-sitemap
    - jekyll-coffeescript
    - jekyll-paginate
  
google_analytics: UA-85988652-1
